set_property PACKAGE_PIN V17 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {A[4]}]
set_property PACKAGE_PIN V15 [get_ports {A[5]}]
set_property PACKAGE_PIN V2  [get_ports {B[0]}]
set_property PACKAGE_PIN T3  [get_ports {B[1]}]
set_property PACKAGE_PIN T2  [get_ports {B[2]}]
set_property PACKAGE_PIN R3  [get_ports {B[3]}]
set_property PACKAGE_PIN W2  [get_ports {B[4]}]
set_property PACKAGE_PIN U1  [get_ports {B[5]}]
set_property PACKAGE_PIN W19 [get_ports {SelectOperation}]

set_property PACKAGE_PIN U16 [get_ports {S[0]}]
set_property PACKAGE_PIN E19 [get_ports {S[1]}]
set_property PACKAGE_PIN U19 [get_ports {S[2]}]
set_property PACKAGE_PIN V19 [get_ports {S[3]}]
set_property PACKAGE_PIN W18 [get_ports {S[4]}]
set_property PACKAGE_PIN U15 [get_ports {S[5]}]
set_property PACKAGE_PIN U14 [get_ports {S[6]}]


set_property IOSTANDARD LVCMOS33 [get_ports {A B SelectOperation S}]
