set_property PACKAGE_PIN V17 [get_ports {Binary[0]}]
set_property PACKAGE_PIN V16 [get_ports {Binary[1]}]
set_property PACKAGE_PIN W16 [get_ports {Binary[2]}]
set_property PACKAGE_PIN W17 [get_ports {Binary[3]}]
set_property PACKAGE_PIN W15 [get_ports {Binary[4]}]
set_property PACKAGE_PIN V15 [get_ports {Binary[5]}]
set_property PACKAGE_PIN W14 [get_ports {Binary[6]}]
set_property PACKAGE_PIN W13 [get_ports {Binary[7]}]

set_property PACKAGE_PIN U16 [get_ports {BCD[0]}]
set_property PACKAGE_PIN E19 [get_ports {BCD[1]}]
set_property PACKAGE_PIN U19 [get_ports {BCD[2]}]
set_property PACKAGE_PIN V19 [get_ports {BCD[3]}]
set_property PACKAGE_PIN W18 [get_ports {BCD[4]}]
set_property PACKAGE_PIN U15 [get_ports {BCD[5]}]
set_property PACKAGE_PIN U14 [get_ports {BCD[6]}]
set_property PACKAGE_PIN V14 [get_ports {BCD[7]}]
set_property PACKAGE_PIN V13 [get_ports {BCD[8]}]
set_property PACKAGE_PIN V3  [get_ports {BCD[9]}]
set_property PACKAGE_PIN W3  [get_ports {BCD[10]}]
set_property PACKAGE_PIN U3  [get_ports {BCD[11]}]
set_property PACKAGE_PIN L1  [get_ports {Negative}]


set_property IOSTANDARD LVCMOS33 [get_ports {Binary BCD Negative}]
