set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ManualClock_IBUF]

set_property PACKAGE_PIN V17 [get_ports {ProgramModeDataIn[0]}]
set_property PACKAGE_PIN V16 [get_ports {ProgramModeDataIn[1]}]
set_property PACKAGE_PIN W16 [get_ports {ProgramModeDataIn[2]}]
set_property PACKAGE_PIN W17 [get_ports {ProgramModeDataIn[3]}]
set_property PACKAGE_PIN W15 [get_ports {ProgramModeDataIn[4]}]
set_property PACKAGE_PIN V15 [get_ports {ProgramModeDataIn[5]}]
set_property PACKAGE_PIN W14 [get_ports {ProgramModeDataIn[6]}]
set_property PACKAGE_PIN W13 [get_ports {ProgramModeDataIn[7]}]
set_property PACKAGE_PIN V2  [get_ports {ProgramModeAddressIn[0]}]
set_property PACKAGE_PIN T3  [get_ports {ProgramModeAddressIn[1]}]
set_property PACKAGE_PIN T2  [get_ports {ProgramModeAddressIn[2]}]
set_property PACKAGE_PIN R3  [get_ports {ProgramModeAddressIn[3]}]
set_property PACKAGE_PIN W2  [get_ports {ProgramModeAddressIn[4]}]
set_property PACKAGE_PIN U1  [get_ports {ProgramModeAddressIn[5]}]
set_property PACKAGE_PIN T1  [get_ports {ProgramModeAddressIn[6]}]
set_property PACKAGE_PIN R2  [get_ports {ProgramModeAddressIn[7]}]

set_property PACKAGE_PIN W5  [get_ports {Clock100MHz}]

set_property PACKAGE_PIN W19 [get_ports {ManualClock}]
set_property PACKAGE_PIN U18 [get_ports {ProgramModeToggle}]
set_property PACKAGE_PIN T18 [get_ports {ProgramModeClock}]
set_property PACKAGE_PIN U17 [get_ports {ClockToggle}]
set_property PACKAGE_PIN T17 [get_ports {Reset}]

set_property PACKAGE_PIN U2  [get_ports {Anodes[0]}]
set_property PACKAGE_PIN U4  [get_ports {Anodes[1]}]
set_property PACKAGE_PIN V4  [get_ports {Anodes[2]}]
set_property PACKAGE_PIN W4  [get_ports {Anodes[3]}]

set_property PACKAGE_PIN U7  [get_ports {LEDs[0]}]
set_property PACKAGE_PIN V5  [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U5  [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V8  [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U8  [get_ports {LEDs[4]}]
set_property PACKAGE_PIN W6  [get_ports {LEDs[5]}]
set_property PACKAGE_PIN W7  [get_ports {LEDs[6]}]

set_property PACKAGE_PIN U16 [get_ports {Bus[0]}]
set_property PACKAGE_PIN E19 [get_ports {Bus[1]}]
set_property PACKAGE_PIN U19 [get_ports {Bus[2]}]
set_property PACKAGE_PIN V19 [get_ports {Bus[3]}]
set_property PACKAGE_PIN W18 [get_ports {Bus[4]}]
set_property PACKAGE_PIN U15 [get_ports {Bus[5]}]
set_property PACKAGE_PIN U14 [get_ports {Bus[6]}]
set_property PACKAGE_PIN V14 [get_ports {Bus[7]}]
set_property PACKAGE_PIN V13 [get_ports {ProgramModeRAMQ[0]}]
set_property PACKAGE_PIN V3  [get_ports {ProgramModeRAMQ[1]}]
set_property PACKAGE_PIN W3  [get_ports {ProgramModeRAMQ[2]}]
set_property PACKAGE_PIN U3  [get_ports {ProgramModeRAMQ[3]}]
set_property PACKAGE_PIN P3  [get_ports {ProgramModeRAMQ[4]}]
set_property PACKAGE_PIN N3  [get_ports {ProgramModeRAMQ[5]}]
set_property PACKAGE_PIN P1  [get_ports {ProgramModeRAMQ[6]}]
set_property PACKAGE_PIN L1  [get_ports {ProgramModeRAMQ[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ProgramModeAddressIn ProgramModeDataIn Clock100MHz ManualClock ProgramModeToggle ProgramModeClock ClockToggle Reset Anodes LEDs Bus ProgramModeRAMQ}]
