set_property PACKAGE_PIN V17 [get_ports {Select[0]}]
set_property PACKAGE_PIN V16 [get_ports {Select[1]}]
set_property PACKAGE_PIN W16 [get_ports {Select[2]}]
set_property PACKAGE_PIN W17 [get_ports {Select[3]}]

set_property PACKAGE_PIN U16 [get_ports {O[0]}]
set_property PACKAGE_PIN E19 [get_ports {O[1]}]
set_property PACKAGE_PIN U19 [get_ports {O[2]}]
set_property PACKAGE_PIN V19 [get_ports {O[3]}]
set_property PACKAGE_PIN W18 [get_ports {O[4]}]
set_property PACKAGE_PIN U15 [get_ports {O[5]}]
set_property PACKAGE_PIN U14 [get_ports {O[6]}]
set_property PACKAGE_PIN V14 [get_ports {O[7]}]
set_property PACKAGE_PIN V13 [get_ports {O[8]}]
set_property PACKAGE_PIN V3  [get_ports {O[9]}]
set_property PACKAGE_PIN W3  [get_ports {O[10]}]
set_property PACKAGE_PIN U3  [get_ports {O[11]}]
set_property PACKAGE_PIN P3  [get_ports {O[12]}]
set_property PACKAGE_PIN N3  [get_ports {O[13]}]
set_property PACKAGE_PIN P1  [get_ports {O[14]}]
set_property PACKAGE_PIN L1  [get_ports {O[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports {Select O}]
