set_property PACKAGE_PIN V17 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {A[4]}]
set_property PACKAGE_PIN V15 [get_ports {A[5]}]
set_property PACKAGE_PIN W14 [get_ports {A[6]}]
set_property PACKAGE_PIN W13 [get_ports {A[7]}]
set_property PACKAGE_PIN V2  [get_ports {B[0]}]
set_property PACKAGE_PIN T3  [get_ports {B[1]}]
set_property PACKAGE_PIN T2  [get_ports {B[2]}]
set_property PACKAGE_PIN R3  [get_ports {B[3]}]
set_property PACKAGE_PIN W2  [get_ports {B[4]}]
set_property PACKAGE_PIN U1  [get_ports {B[5]}]
set_property PACKAGE_PIN T1  [get_ports {B[6]}]
set_property PACKAGE_PIN R2  [get_ports {B[7]}]

set_property PACKAGE_PIN W5  [get_ports {Clock100MHz}]
set_property PACKAGE_PIN W19 [get_ports {SelectOperation}]

set_property PACKAGE_PIN U7  [get_ports {LEDs[0]}]
set_property PACKAGE_PIN V5  [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U5  [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V8  [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U8  [get_ports {LEDs[4]}]
set_property PACKAGE_PIN W6  [get_ports {LEDs[5]}]
set_property PACKAGE_PIN W7  [get_ports {LEDs[6]}]

set_property PACKAGE_PIN U2  [get_ports {Anodes[0]}]
set_property PACKAGE_PIN U4  [get_ports {Anodes[1]}]
set_property PACKAGE_PIN V4  [get_ports {Anodes[2]}]
set_property PACKAGE_PIN W4  [get_ports {Anodes[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports {A B Clock100MHz SelectOperation LEDs Anodes}]
