set_property PACKAGE_PIN V17 [get_ports {Instruction[0]}]
set_property PACKAGE_PIN V16 [get_ports {Instruction[1]}]
set_property PACKAGE_PIN W16 [get_ports {Instruction[2]}]
set_property PACKAGE_PIN W17 [get_ports {Instruction[3]}]
set_property PACKAGE_PIN W15 [get_ports {Instruction[4]}]
set_property PACKAGE_PIN V15 [get_ports {Instruction[5]}]
set_property PACKAGE_PIN W14 [get_ports {Instruction[6]}]
set_property PACKAGE_PIN W13 [get_ports {Instruction[7]}]
set_property PACKAGE_PIN V2  [get_ports {Instruction[8]}]
set_property PACKAGE_PIN T3  [get_ports {Instruction[9]}]
set_property PACKAGE_PIN T2  [get_ports {Instruction[10]}]
set_property PACKAGE_PIN R3  [get_ports {Instruction[11]}]
set_property PACKAGE_PIN W2  [get_ports {Instruction[12]}]
set_property PACKAGE_PIN U1  [get_ports {Instruction[13]}]

set_property PACKAGE_PIN U16 [get_ports {ControlWord[0]}]
set_property PACKAGE_PIN E19 [get_ports {ControlWord[1]}]
set_property PACKAGE_PIN U19 [get_ports {ControlWord[2]}]
set_property PACKAGE_PIN V19 [get_ports {ControlWord[3]}]
set_property PACKAGE_PIN W18 [get_ports {ControlWord[4]}]
set_property PACKAGE_PIN U15 [get_ports {ControlWord[5]}]
set_property PACKAGE_PIN U14 [get_ports {ControlWord[6]}]
set_property PACKAGE_PIN V14 [get_ports {ControlWord[7]}]
set_property PACKAGE_PIN V13 [get_ports {ControlWord[8]}]
set_property PACKAGE_PIN V3  [get_ports {ControlWord[9]}]
set_property PACKAGE_PIN W3  [get_ports {ControlWord[10]}]
set_property PACKAGE_PIN U3  [get_ports {ControlWord[11]}]
set_property PACKAGE_PIN P3  [get_ports {ControlWord[12]}]
set_property PACKAGE_PIN N3  [get_ports {ControlWord[13]}]
set_property PACKAGE_PIN P1  [get_ports {ControlWord[14]}]
set_property PACKAGE_PIN L1  [get_ports {ControlWord[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports {Instruction ControlWord}]
